# Generated by Django 4.0.3 on 2022-03-17 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_social_facebook_profile_social_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.service'),
        ),
    ]
